### ISSUE TITLE
Take the socials toggle to right side

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/analog-clock#52] opened 2022-10-28 09:52 UTC

**Comment by devika-singh** [comment] 2022-12-03 16:33
Can I be assigned this issue?

**Comment by Gaurav945572** [comment] 2022-12-04 17:21
Please assign me this task

**Comment by iamatifmoin** [comment] 2022-12-05 06:47
@boradesanket13 
I have resolved the issue. Please review the PR.

**Comment by SattyamSamania** [comment] 2022-12-05 15:24
Hey @boradesanket13 If the issue is still open can I work on this?

**Comment by boradesanket13** [comment] 2022-12-07 12:56
> @boradesanket13 I have resolved the issue. Please review the PR.


Thanks for your interest! Get issues assigned before writing code from next time.  Happy Hacking!🚀

**Closed** 2022-12-07 12:59 UTC
Labels: Easy, Codepeak 2022
