### ISSUE TITLE
Centre align the quotes

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/analog-clock#53] opened 2022-10-28 09:53 UTC

**Comment by devika-singh** [comment] 2022-12-03 16:30
Hey ... can I be assigned this?

**Comment by devika-singh** [comment] 2022-12-03 16:57
I did a pull request for the same please review it?

**Comment by devika-singh** [comment] 2022-12-03 17:12
Yeah sorry about that I thougth coding period started

**Comment by pranavajith** [comment] 2022-12-04 07:17
Hey @boradesanket13 
Could you assign me this issue?

**Comment by ankushj0801** [comment] 2022-12-04 15:58
I would like to work on this please assign it to me

**Comment by sankooru14** [comment] 2022-12-05 07:19
@boradesanket13 Please assign this issue to me

**Comment by Abhijeet-2003** [comment] 2022-12-06 07:39
I would like to work on this @boradesanket13

**Comment by Abhijeet-2003** [comment] 2022-12-11 22:26
if the issue is still open, please assign it to me. @boradesanket13

**Closed** 2022-12-26 12:42 UTC
Labels: Easy, Codepeak 2022
